title: Kaden5480
email: kaden5480@protonmail.com
github_username: Kaden5480

domain: kaden5480.github.io
url: "https://kaden5480.github.io"
description: Unity modder and Peaks of Yore speedrunner.
theme: minima
include:
  - uilib

avatar_link: https://avatars.githubusercontent.com/u/67208843
unity_link: https://unity.com/
peaks_link: https://store.steampowered.com/app/2236070/
github_link: https://github.com/Kaden5480
